# Question1

In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [5]:
l=np.array([int(input()) for i in range(5)])
m=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((l,m))))

10
30
50
70
90
20
40
60
80
100
[ 10  20  30  40  50  60  70  80  90 100]


# Question 3

In [8]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.ndim)
print(arr.size)

2
9


# Question 4

In [14]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2.shape)

(6,)
(1, 6)


In [16]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
b = np.expand_dims(a, axis=0)
print(b.shape)

(6,)
(1, 6)


In [17]:
#here we changed 1D to 2D using newaxis and expand_dims

# Question 5

In [19]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.hstack(l))
print(np.vstack(l))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Question 6

In [21]:
l=np.arange(1,10)
print(np.unique(l,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))


In [ ]:
#--------------------------------------------------------------------------------------